### ISSUE TITLE
AutoRest C# generator generating DPG code with compilation errors

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/autorest.csharp#2766]
We are trying to generate DPG code for the swaggers listed [here](https://github.com/Azure/azure-sdk-for-net/blob/2ed2c1d5aa3576f556216a9da95600fa8b52a71f/sdk/devcenter/Azure.Developer.DevCenter/src/autorest.md) and we are getting [these](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1914087&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=a880e989-7d1a-5c96-a41f-d540b383cc43&l=69) errors for most of the methods:

> Error CS1737: Optional parameters must appear after all required parameters

For more details please see the failures in https://github.com/Azure/azure-sdk-for-net/pull/31636 PR
